apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-core-deployment
  labels:
    dotnet-core: api
spec:
  replicas: 1
  selector:
    matchLabels:
      dotnet-core: api
  template:
    metadata:
      labels:
        dotnet-core: api
    spec:
      containers:
      - name: dotnet-core-api
        image: dotnet-core-api
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-core-api-service
spec:
  type: NodePort
  selector:
    dotnet-core: api
  ports:
    - port: 80
      # the service binding into the docker container port 
      targetPort: 80
      protocol: TCP
      # the port that will be exposed within the cluster
      nodePort: 30001
      